### ISSUE TITLE
what the street site not found in web search

### ISSUE THREAD

**Issue by mszell** [moovel/lab-what-the-street#110]
Not sure who the right person is to look at this (assigned rapha, you are welcome :p), but when searching for
`what the street moovel`
I get the below results, which does not include the main site itself!
Is there the possibiilty for some SEO or webmaster tool vooodoo? https://www.google.com/webmasters
Or do we just need to wait? Not extremely high prio, but wouldn't be bad either to get this up, I guess.

<img width="608" alt="screen shot 2017-06-27 at 7 36 27 pm" src="https://user-images.githubusercontent.com/9054982/27614473-f7e5c706-5b6f-11e7-8d28-9bfac6176b26.png">

**Comment by mszell** [comment]
Still the same. Was there any progress on this? Strange that it does not show up at all.

**Comment by rraapphhaaeell** [comment]
I've reached out to our performance marketing guys to see how they do it. If that doesn't help I'll see what I can do myself 👻

**Comment by tdurand** [comment]
It is showing up now
