### ISSUE TITLE
SSL now activated

### ISSUE THREAD

**Issue by rraapphhaaeell** [moovel/lab-what-the-street#118]
I activated SSL, we can now get ready from app side (some routings are HTTP). Let me know when to deploy.

**Comment by tdurand** [comment]
Great, I've switched bunch of hardcoded http to https but it seems there is a bigger issue I can't test with the little time I have tonight.

The client side app register the baseUrl with that code (it is 6 time in the code base), and seems the protocol is not returning https as it should : https://github.com/moovel/lab-what-the-street/blob/master/pages/explore.js#L21 , we could replace that to an hardcoded "https" but then it wouldn't work on localhost.

I think it's better if you wait that I'm back also I can setup 301 redirect on the node.js server http -> https.

I'll be able to work on that on the week of the 25th of july.

**Comment by tdurand** [comment]
I'm sorry @rraapphhaaeell , Last week has been pretty busy and I forgot about this one, I can see this matter beginning of this week , but maybe you are off for holidays also ;-)

**Comment by rraapphhaaeell** [comment]
no prob! I'm ready to deploy any time :>

**Comment by tdurand** [comment]
Ok will do this afternoon, ping you when done to deploy

**Comment by tdurand** [comment]
ok should work now and redirect to HTTPS by default
