### ISSUE TITLE
implement new mapbox key & account 

### ISSUE THREAD

**Issue by rraapphhaaeell** [moovel/lab-what-the-street#119]
we still need to add styles. Will do that tomorrow then it is ready for implementation into tool. Will let you know as soon as we're ready for implementation.

**Comment by tdurand** [comment]
Ok, I'm gonna be in holidays starting tomorrow, so if you want to change that meanwhile I'm off, you need to change:

- Token in the config.json file
- Change here the **userName/mapId** for the satellite tiles of the map: https://github.com/moovel/lab-what-the-street/blob/master/app/statemanagement/constants/identifiersConstants.js#L9
- Change here the **userName/mapId** for the satellite tiles of the gif, it was with less contrast: https://github.com/moovel/lab-what-the-street/blob/master/app/mapmobile/MapMobile.js#L94
