### ISSUE TITLE
mapbox styles

### ISSUE THREAD

**Issue by rraapphhaaeell** [moovel/lab-what-the-street#123]
after discussing with mapbox we need to revert https://github.com/moovel/lab-what-the-street/commit/6f7cdb17ad083ea066e561c86cd33cb30c94cb6f again. Back to /moovellab style and API-Key.

**Comment by tdurand** [comment]
should I do something here also ?

**Comment by tdurand** [comment]
ok done, but you'll need to change the Token in the config file for that to work ;-)

**Comment by rraapphhaaeell** [comment]
already prepared that :> thx
