### ISSUE TITLE
preparation for Path based access

### ISSUE THREAD

**Issue by florianporada** [moovel/lab-what-the-street#126]
I added the URL_PREFIX and ROOT_URL vars to our CDCI pipeline. 
So everything should be ready when you refactor the project. ✌️

**Comment by tdurand** [comment]
Yes I'm on it now.. It is super painfull because I need to upgrade next, which needs to upgrade react which needs to upgrade X.... 🤒 Oldest project, more painfull !

**Comment by florianporada** [comment]
That's the problem with legacy code. I feel your pain. 🤯
Best luck with the update. 🙏

**Comment by tdurand** [comment]
Done, but here are two/three minor things pending what I can't resolve myself:

- [ ] Will https://s3-eu-west-1.amazonaws.com/gif.whatthestreet.moovellab.com change ? it is a s3 bucket where we are storing all the generated GIF... If so need to update this url in a bunch of places

- [ ] What the street relies on this php script: https://lab.moovel.com/wts-card-video.php to preview the twitter gif of uncoiling when sharing... Make sure you are 301 redirect it when migrating the lab website.. otherwise we will need to update this link and host it somewhere else..

**Comment by tdurand** [comment]
+ Make sure to migrate the mongodb

**Comment by florianporada** [comment]
Hi @tdurand , 
sorry for the late reply. The past few days were pretty packed. 
- I will update the URL for the S3 bucket as soon as the new one is up.
- I put the link to the redirect list or will change it as soon as the new Url is up.
- I thought this mongodb instance is just for caching data or will there be persistent data stored?

**Comment by florianporada** [comment]
One other thing I encountered is, that the uncoiling animation for streets is not working on the new structure:
- https://whatthestreet.moovellab.com/london/explore/car/lanes/130?bike=0.27&rail=0.46&car=0.27
- https://lab.prod.ext.moovel.com/project/whatthestreet/london/explore/car/lanes/130?bike=0.27&rail=0.46&car=0.27 (dev url)

..it seems like the request to the s3 bucket is not happening on the new structure. Do you know when and where the request ist triggered? ... if it's a shape or area the animation is happening.
..or is this data stored in the mongodb? (which relates then to point 3 on my former comment)

**Comment by tdurand** [comment]
Hello Florian, yes the coils are stored in the mongodb that is why we need to migrate it

**Comment by florianporada** [comment]
Alright, i'll set up a mongodb in the env and migrate the data

**Comment by tdurand** [comment]
💪 !

**Comment by florianporada** [comment]
Was finally able to migrate the db. Kept running into memory issues during the import process. 😬

**Comment by tdurand** [comment]
Great, everything working smoothly ?

**Comment by florianporada** [comment]
Yes so far it works. The only thing is the s3 bucket. I already created a new bucket in the new env. 
Do you think we can introduce a env var e.g. `S3_GIF_BUCKET` to keep in dynamic? 
Then I can inject the new URL during startup or deployment.

**Comment by tdurand** [comment]
Done: you can specify the S3_GIF_BUCKET env var.

It needs to be the full URL: example: S3_GIF_BUCKET="https://s3-eu-west-1.amazonaws.com/gif.whatthestreet.moovellab.com"

**Comment by florianporada** [comment]
So I think we can close this issue.

thanks for the help @tdurand 👍
